---
title: "Xenium FFPE Human Lung Cancer with Multimodal Cell Segmentation"
output: 
  html_document:
    number_sections: true
    toc: true
pkgdown:
  as_is: true
vignette: >
  %\VignetteIndexEntry{Xenium FFPE Human Lung Cancer with Multimodal Cell Segmentation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


# Install extra package: _arrow_

Xenium datasets requires arrow with 'ZTSD' support to be installed to work with parquet files.
This is optional if you want to use a different format for the tabular data.
```{r, eval = FALSE}
if (!requireNamespace("arrow", quietly = TRUE)) {
  # install with compression library needed for 10x parquet files
  Sys.setenv(ARROW_WITH_ZSTD = "ON") 
  install.packages("arrow", repos = c("https://apache.r-universe.dev"))
}

# check arrow_info() to see that zstd support should be TRUE
# See https://arrow.apache.org/docs/r/articles/install.html for details
zstd <- arrow::arrow_info()$capabilities[["zstd"]]
if (!zstd) {
  stop("arrow needs to be reinstalled with the command above.")
}
```




```{r, eval=FALSE}
library(Giotto)

# 1. ** SET WORKING DIRECTORY WHERE PROJECT OUPUTS WILL SAVE TO **
results_folder = '/path/to/save/directory/'

# 2. Create Giotto instructions
# Directly saving plots to the working directory without rendering them in the editor saves time.
instrs = createGiottoInstructions(save_dir = results_folder,
                                  save_plot = TRUE,
                                  show_plot = FALSE,
                                  return_plot = FALSE)
```
